force-app/main/default/objects/DWCustomer__c/DWCustomer__c.object-meta.xml
<CustomObject>
    <label>DWCustomer</label>
    <nameField>
        <label>DWCustomer Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DWCustomers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DWCustomer__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DWCustomers (Account)</relationshipLabel>
    <relationshipName>DWCustomers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_1__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_1__c</fullName>
    <label>CUSTOMER_ADDRESS_1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_2__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_2__c</fullName>
    <label>CUSTOMER_ADDRESS_2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_3__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_3__c</fullName>
    <label>CUSTOMER_ADDRESS_3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_4__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_4__c</fullName>
    <label>CUSTOMER_ADDRESS_4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_5__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_5__c</fullName>
    <label>CUSTOMER_ADDRESS_5</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_COUNTRY_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_COUNTRY_CODE__c</fullName>
    <label>CUSTOMER_COUNTRY_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_POSTAL_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_POSTAL_CODE__c</fullName>
    <label>CUSTOMER_POSTAL_CODE</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DWCustomers (Parent Account)</relationshipLabel>
    <relationshipName>DWCustomers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SALES_PERSON__c.field-meta.xml
<CustomField>
    <fullName>SALES_PERSON__c</fullName>
    <label>Sales Person</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/Ship_To_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliation #</label>
    <referenceTo>Ship_To_Affiliation__c</referenceTo>
    <relationshipLabel>DWCustomers</relationshipLabel>
    <relationshipName>DWCustomers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_CUSTOMER__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_CUSTOMER__c</fullName>
    <label>SHIPTO_CUSTOMER</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_CUSTOMER_CODE__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_CUSTOMER_CODE__c</fullName>
    <label>SHIPTO_CUSTOMER_CODE</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_NETSALES_CYTD__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_NETSALES_CYTD__c</fullName>
    <label>Sales This Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_NETSALES_DIFF_YTD__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_NETSALES_DIFF_YTD__c</fullName>
    <description>Ship to Current YTD vs Prior YTD Sales</description>
    <formula>SHIPTO_NETSALES_CYTD__c - SHIPTO_NETSALES_PYTD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SHIPTO_NETSALES_DIFF_YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_NETSALES_PY__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_NETSALES_PY__c</fullName>
    <label>NetSales PY</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_NETSALES_PYTD__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_NETSALES_PYTD__c</fullName>
    <label>Sales Last Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SOLDTO_CUSTOMER__c.field-meta.xml
<CustomField>
    <fullName>SOLDTO_CUSTOMER__c</fullName>
    <label>Sold To Customer</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/Total_Previous_Year_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Previous_Year_Sales__c</fullName>
    <formula>SHIPTO_NETSALES_PY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Previous Year Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/Ship_To_Affiliation__c.object-meta.xml
<CustomObject>
    <label>Affiliated Account</label>
    <nameField>
        <displayFormat>AFF-{00000}</displayFormat>
        <label>Affiliation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated Accounts (Account)</relationshipLabel>
    <relationshipName>Ship_To_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <label>Address 3</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Affiliated_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Affiliated_Account_Name__c</fullName>
    <label>Affiliated Ship To Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Affiliated_Sold_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Affiliated_Sold_To_Account__c</fullName>
    <label>Affiliated Sold To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Aurora_Location__c.field-meta.xml
<CustomField>
    <fullName>Aurora_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aurora Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Affiliated Accounts</relationshipLabel>
    <relationshipName>Affiliated_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/DWCustomer_Record__c.field-meta.xml
<CustomField>
    <fullName>DWCustomer_Record__c</fullName>
    <label>DWCustomer Record</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated Accounts (Parent Account)</relationshipLabel>
    <relationshipName>Ship_To_Affiliation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Sales_in_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_in_Current_Year__c</fullName>
    <label>Sales in Current Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Sales_in_Last_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_in_Last_Year__c</fullName>
    <label>Sales in Last Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <label>Sales Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Affiliated Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <label>Sold To Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Total_Previous_Year_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Previous_Year_Sales__c</fullName>
    <label>Total Previous Year Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Total_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales__c</fullName>
    <label>Total Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/YTD_Sale_Difference__c.field-meta.xml
<CustomField>
    <fullName>YTD_Sale_Difference__c</fullName>
    <label>YTD Sale Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DWCustomerShiptoAffHandler.cls
public class DWCustomerShiptoAffHandler {
    
    public static void BeforeHandler(list<DWCustomer__c> BeforeList)
    {
        set<ID> accnid= new set<id>();
        Integer count;
        list<Ship_To_Affiliation__c> afflist= new list<Ship_To_Affiliation__c>();
        
        list<Ship_To_Affiliation__c> shiptoaff=[SELECT Id,Affiliated_Account_Name__c,Affiliated_Sold_To_Account__c,Sales_Person__c,Zip_Postal_Code__c,Address_1__c,Address_2__c,Address_3__c,Total_Sales__c,Sales_in_Last_Year__c,Sales_in_Current_Year__c,City__c, Name,State_Province__c,Country__c, Account__c,Account__r.ParentId ,Ship_To_Code__c, Sold_To_Code__c, Aurora_Location__c FROM Ship_To_Affiliation__c where Ship_To_Code__c!=null ];
        
        for(DWCustomer__c dw:BeforeList)
        {
            for(Ship_To_Affiliation__c sf:shiptoaff)
            {
                if(dw.SHIPTO_CUSTOMER_CODE__c==sf.Ship_To_Code__c)
                {
                    dw.Ship_To_Affiliation__c=sf.id;
                    dw.Account_Name__c=sf.Account__c;
                    dw.Parent_Account__c=sf.Account__r.ParentId;
                }
                if(dw.SHIPTO_CUSTOMER_CODE__c==sf.Ship_To_Code__c)
                {
                    sf.Address_1__c=dw.CUSTOMER_ADDRESS_1__c;
                    sf.Address_2__c=dw.CUSTOMER_ADDRESS_2__c;
                    sf.Address_3__c=dw.CUSTOMER_ADDRESS_3__c;
                    sf.City__c=dw.CUSTOMER_ADDRESS_4__c;
                    sf.State_Province__c=dw.CUSTOMER_ADDRESS_5__c;
                    sf.Zip_Postal_Code__c=dw.CUSTOMER_POSTAL_CODE__c;
                    sf.Country__c=dw.CUSTOMER_COUNTRY_CODE__c;
                    sf.Sales_Person__c=dw.SALES_PERSON__c;
                    sf.Affiliated_Account_Name__c=dw.SHIPTO_CUSTOMER__c;
                    sf.Affiliated_Sold_To_Account__c=dw.SOLDTO_CUSTOMER__c;
                    afflist.add(sf);
                }
                
            }
            
        }
        
        update afflist;
    }
    public static void AfterHandler(list<DWCustomer__c> AfterList)
    {
        set<ID> accnid= new set<id>();
        Integer count;
        if(checkRecursive3.runOnce()){
            
        list<Ship_To_Affiliation__c> afflist= new list<Ship_To_Affiliation__c>();
        for(DWCustomer__c dw:AfterList)
        {
            accnid.add(dw.Ship_To_Affiliation__c);
        }
        list<Ship_To_Affiliation__c> shiptoaff1=[SELECT Id,Total_Sales__c,Total_Previous_Year_Sales__c,YTD_Sale_Difference__c,DWCustomer_Record__c,Sales_in_Last_Year__c,Sales_in_Current_Year__c,City__c FROM Ship_To_Affiliation__c where ID IN:accnid];
        list<DWCustomer__c> custlist1=[select id,SHIPTO_NETSALES_PY__c,SHIPTO_NETSALES_PYTD__c,SHIPTO_NETSALES_DIFF_YTD__c,SHIPTO_NETSALES_CYTD__c,Ship_To_Affiliation__c from DWCustomer__c where Ship_To_Affiliation__c IN : accnid];
        
        for(Ship_To_Affiliation__c sh:shiptoaff1)
        {
            for(DWCustomer__c dc:custlist1)
            {
                // to update record id in aff account 
                sh.DWCustomer_Record__c=dc.id;
                // end....
                
                Decimal d=0;
                Decimal d1=0;
                Decimal d2=0;
                Decimal d3=0;
                Decimal d4=0;
                for(DWCustomer__c dw1:custlist1)
                {
                    if(dw1.SHIPTO_NETSALES_CYTD__c!=null)
                    {
                        d=d+dw1.SHIPTO_NETSALES_CYTD__c;  
                    }
                    if(dw1.SHIPTO_NETSALES_PYTD__c!=null)
                    {
                        d1=d1+dw1.SHIPTO_NETSALES_PYTD__c;
                    }
                    if(dw1.SHIPTO_NETSALES_DIFF_YTD__c!=null)
                    {
                        d3=d3+dw1.SHIPTO_NETSALES_DIFF_YTD__c;
                    }
                    if(dw1.SHIPTO_NETSALES_PY__c!=null)
                    {
                        d4=d4+dw1.SHIPTO_NETSALES_PY__c;
                    }
                    
                    d2=d+d1;
                }
                sh.Sales_in_Current_Year__c=d;
                sh.Sales_in_Last_Year__c=d1;
                sh.Total_Sales__c=d2;
                sh.YTD_Sale_Difference__c=d3;
                sh.Total_Previous_Year_Sales__c=d4;
            }
        }
        
        update shiptoaff1; 
        
    }
}
}