force-app/main/default/objects/DWCustomer__c/DWCustomer__c.object-meta.xml
<CustomObject>
    <label>DWCustomer</label>
    <nameField>
        <label>DWCustomer Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DWCustomers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_CORPORATION__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_CORPORATION__c</fullName>
    <label>CUSTOMER_CORPORATION</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_CORPORATION_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_CORPORATION_CODE__c</fullName>
    <label>CUSTOMER_CORPORATION_CODE</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_COUNTRY__c</fullName>
    <label>CUSTOMER_COUNTRY</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_COUNTRY_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_COUNTRY_CODE__c</fullName>
    <label>CUSTOMER_COUNTRY_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_INDUSTRY__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_INDUSTRY__c</fullName>
    <label>CUSTOMER_INDUSTRY</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_INDUSTRY_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_INDUSTRY_CODE__c</fullName>
    <label>CUSTOMER_INDUSTRY_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_KEY__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_KEY__c</fullName>
    <externalId>true</externalId>
    <label>CUSTOMER_KEY</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_PAYMENT_METHOD__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_PAYMENT_METHOD__c</fullName>
    <label>CUSTOMER_PAYMENT_METHOD</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_REGION__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_REGION__c</fullName>
    <label>CUSTOMER_REGION</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_REGION_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_REGION_CODE__c</fullName>
    <label>CUSTOMER_REGION_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_SALES_GROUP__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_SALES_GROUP__c</fullName>
    <label>CUSTOMER_SALES_GROUP</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_SEGMENT__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_SEGMENT__c</fullName>
    <label>CUSTOMER_SEGMENT</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_SEGMENT_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_SEGMENT_CODE__c</fullName>
    <label>CUSTOMER_SEGMENT_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_STATE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_STATE__c</fullName>
    <label>CUSTOMER_STATE</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_STATE_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_STATE_CODE__c</fullName>
    <label>CUSTOMER_STATE_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_STATUS__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_STATUS__c</fullName>
    <label>CUSTOMER_STATUS</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_TERMS_DAYS__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_TERMS_DAYS__c</fullName>
    <label>CUSTOMER_TERMS_DAYS</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_TERRITORY__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_TERRITORY__c</fullName>
    <label>CUSTOMER_TERRITORY</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_TERRITORY_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_TERRITORY_CODE__c</fullName>
    <label>CUSTOMER_TERRITORY_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_TYPE__c</fullName>
    <label>CUSTOMER_TYPE</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_TYPE_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_TYPE_CODE__c</fullName>
    <label>CUSTOMER_TYPE_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SALES_PERSON__c.field-meta.xml
<CustomField>
    <fullName>SALES_PERSON__c</fullName>
    <label>Sales Person</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SALES_PERSON_CODE__c.field-meta.xml
<CustomField>
    <fullName>SALES_PERSON_CODE__c</fullName>
    <label>SALES_PERSON_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/Ship_To_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliation #</label>
    <referenceTo>Ship_To_Affiliation__c</referenceTo>
    <relationshipLabel>DWCustomers</relationshipLabel>
    <relationshipName>DWCustomers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_CUSTOMER__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_CUSTOMER__c</fullName>
    <label>SHIPTO_CUSTOMER</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_CUSTOMER_CODE__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_CUSTOMER_CODE__c</fullName>
    <label>SHIPTO_CUSTOMER_CODE</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SOLDTO_CUSTOMER__c.field-meta.xml
<CustomField>
    <fullName>SOLDTO_CUSTOMER__c</fullName>
    <label>Sold To Customer</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SOLDTO_CUSTOMER_CODE__c.field-meta.xml
<CustomField>
    <fullName>SOLDTO_CUSTOMER_CODE__c</fullName>
    <label>SOLDTO_CUSTOMER_CODE</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/Ship_To_Affiliation__c.object-meta.xml
<CustomObject>
    <label>Affiliated Account</label>
    <nameField>
        <displayFormat>AFF-{00000}</displayFormat>
        <label>Affiliation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated Accounts (Account)</relationshipLabel>
    <relationshipName>Ship_To_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <label>Sales Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Affiliated Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShipToAffAdressHandlerTest.cls
@isTest
public class ShipToAffAdressHandlerTest {
    
    @isTest
    public static void testmethod1()
    {
        Account acc= new Account();
        acc.Name='Test';
        insert acc;
        
        DWCustomer__c dw= new DWCustomer__c();
        dw.Name='';
        dw.CUSTOMER_KEY__c=45664.56;
        dw.CUSTOMER_TYPE_CODE__c='BW';
        dw.CUSTOMER_TYPE__c='Brewing Market';
        dw.CUSTOMER_SALES_GROUP__c='Small Account';
        dw.CUSTOMER_SEGMENT_CODE__c='XX';
        dw.CUSTOMER_SEGMENT__c='XX-Classification not used';
        dw.CUSTOMER_INDUSTRY_CODE__c='BXC';
        dw.CUSTOMER_INDUSTRY__c='Brewing-Craft';
        dw.SALES_PERSON__c='Chris Webster';
        dw.CUSTOMER_REGION_CODE__c='CN';
        dw.CUSTOMER_REGION__c='Canada';
        dw.CUSTOMER_COUNTRY_CODE__c='BR';
        dw.CUSTOMER_COUNTRY__c='Canada';
        dw.CUSTOMER_TERRITORY_CODE__c='02';
        dw.CUSTOMER_TERRITORY__c='Fresno-based Customer';
        dw.CUSTOMER_STATE_CODE__c='BC';
        dw.CUSTOMER_STATE__c='Canada, British Columbia';
        dw.CUSTOMER_STATUS__c='Open Account';
        dw.CUSTOMER_PAYMENT_METHOD__c='@ERR';
        dw.CUSTOMER_TERMS_DAYS__c='0';
        dw.CUSTOMER_CORPORATION_CODE__c='999';
        dw.CUSTOMER_CORPORATION__c='Test';
        dw.SOLDTO_CUSTOMER_CODE__c='590193-000';
        dw.SOLDTO_CUSTOMER__c='Red Truck Beer Company';
        dw.SHIPTO_CUSTOMER_CODE__c='5789456-791040';
        dw.SHIPTO_CUSTOMER__c='Red Truck Beer Company';
        dw.SYS_CREATED__c=system.today();
        dw.SYS_UPDATED__c=system.today();
        dw.SALES_PERSON_CODE__c='CB';
        insert dw;
        
        
        Ship_To_Affiliation__c sf =new Ship_To_Affiliation__c();
        sf.Account__c=acc.id;
        sf.Ship_To_Code__c='5789456-791040';
        insert sf;
        sf.Ship_To_Code__c='5789456-791040';
        update sf;
      
    } 
     @isTest
    public static void testmethod2()
    {
         Account acc= new Account();
        acc.Name='Test';
        insert acc;
        
         Ship_To_Affiliation__c sf =new Ship_To_Affiliation__c();
        sf.Account__c=acc.id;
        sf.Ship_To_Code__c='5789456-791041';
        insert sf;
        
         DWCustomer__c dw= new DWCustomer__c();
        dw.Name='';
        dw.CUSTOMER_KEY__c=45664.56;
        dw.CUSTOMER_TYPE_CODE__c='BW';
        dw.CUSTOMER_TYPE__c='Brewing Market';
        dw.CUSTOMER_SALES_GROUP__c='Small Account';
        dw.CUSTOMER_SEGMENT_CODE__c='XX';
        dw.CUSTOMER_SEGMENT__c='XX-Classification not used';
        dw.CUSTOMER_INDUSTRY_CODE__c='BXC';
        dw.CUSTOMER_INDUSTRY__c='Brewing-Craft';
        dw.SALES_PERSON__c='Chris Webster';
        dw.CUSTOMER_REGION_CODE__c='CN';
        dw.CUSTOMER_REGION__c='Canada';
        dw.CUSTOMER_COUNTRY_CODE__c='BR';
        dw.CUSTOMER_COUNTRY__c='Canada';
        dw.CUSTOMER_TERRITORY_CODE__c='02';
        dw.CUSTOMER_TERRITORY__c='Fresno-based Customer';
        dw.CUSTOMER_STATE_CODE__c='BC';
        dw.CUSTOMER_STATE__c='Canada, British Columbia';
        dw.CUSTOMER_STATUS__c='Open Account';
        dw.CUSTOMER_PAYMENT_METHOD__c='@ERR';
        dw.CUSTOMER_TERMS_DAYS__c='0';
        dw.CUSTOMER_CORPORATION_CODE__c='999';
        dw.CUSTOMER_CORPORATION__c='Test';
        dw.SOLDTO_CUSTOMER_CODE__c='590193-000';
        dw.SOLDTO_CUSTOMER__c='Red Truck Beer Company';
        dw.SHIPTO_CUSTOMER_CODE__c='5789456-791040';
        dw.SHIPTO_CUSTOMER__c='Red Truck Beer Company';
        dw.SYS_CREATED__c=system.today();
        dw.SYS_UPDATED__c=system.today();
        dw.SALES_PERSON_CODE__c='CB';
        dw.Ship_To_Affiliation__c=sf.id;
        insert dw;
    }
   
}