force-app/main/default/objects/DWCustomer__c/DWCustomer__c.object-meta.xml
<CustomObject>
    <label>DWCustomer</label>
    <nameField>
        <label>DWCustomer Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DWCustomers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DWCustomer__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DWCustomers (Account)</relationshipLabel>
    <relationshipName>DWCustomers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_1__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_1__c</fullName>
    <label>CUSTOMER_ADDRESS_1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_2__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_2__c</fullName>
    <label>CUSTOMER_ADDRESS_2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_3__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_3__c</fullName>
    <label>CUSTOMER_ADDRESS_3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_4__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_4__c</fullName>
    <label>CUSTOMER_ADDRESS_4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_ADDRESS_5__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_ADDRESS_5__c</fullName>
    <label>CUSTOMER_ADDRESS_5</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_CORPORATION_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_CORPORATION_CODE__c</fullName>
    <label>CUSTOMER_CORPORATION_CODE</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_COUNTRY__c</fullName>
    <label>CUSTOMER_COUNTRY</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_COUNTRY_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_COUNTRY_CODE__c</fullName>
    <label>CUSTOMER_COUNTRY_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_POSTAL_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_POSTAL_CODE__c</fullName>
    <label>CUSTOMER_POSTAL_CODE</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_STATE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_STATE__c</fullName>
    <label>CUSTOMER_STATE</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/CUSTOMER_STATE_CODE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_STATE_CODE__c</fullName>
    <label>CUSTOMER_STATE_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DWCustomers (Parent Account)</relationshipLabel>
    <relationshipName>DWCustomers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SALES_PERSON__c.field-meta.xml
<CustomField>
    <fullName>SALES_PERSON__c</fullName>
    <label>Sales Person</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/Ship_To_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliation #</label>
    <referenceTo>Ship_To_Affiliation__c</referenceTo>
    <relationshipLabel>DWCustomers</relationshipLabel>
    <relationshipName>DWCustomers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_CUSTOMER__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_CUSTOMER__c</fullName>
    <label>SHIPTO_CUSTOMER</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_CUSTOMER_CODE__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_CUSTOMER_CODE__c</fullName>
    <label>SHIPTO_CUSTOMER_CODE</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_NETSALES_CYTD__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_NETSALES_CYTD__c</fullName>
    <label>Sales This Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SHIPTO_NETSALES_PYTD__c.field-meta.xml
<CustomField>
    <fullName>SHIPTO_NETSALES_PYTD__c</fullName>
    <label>Sales Last Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/SOLDTO_CUSTOMER_CODE__c.field-meta.xml
<CustomField>
    <fullName>SOLDTO_CUSTOMER_CODE__c</fullName>
    <label>SOLDTO_CUSTOMER_CODE</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWCustomer__c/fields/Total_Previous_Year_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Previous_Year_Sales__c</fullName>
    <formula>SHIPTO_NETSALES_PY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Previous Year Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/Ship_To_Affiliation__c.object-meta.xml
<CustomObject>
    <label>Affiliated Account</label>
    <nameField>
        <displayFormat>AFF-{00000}</displayFormat>
        <label>Affiliation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated Accounts (Account)</relationshipLabel>
    <relationshipName>Ship_To_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated Accounts (Parent Account)</relationshipLabel>
    <relationshipName>Ship_To_Affiliation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Sales_in_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_in_Current_Year__c</fullName>
    <label>Sales in Current Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Sales_in_Last_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_in_Last_Year__c</fullName>
    <label>Sales in Last Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <label>Sales Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Affiliated Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Total_Previous_Year_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Previous_Year_Sales__c</fullName>
    <label>Total Previous Year Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Total_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales__c</fullName>
    <label>Total Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/YTD_Sale_Difference__c.field-meta.xml
<CustomField>
    <fullName>YTD_Sale_Difference__c</fullName>
    <label>YTD Sale Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ShipToAffAdressHandler.cls
public class ShipToAffAdressHandler {
    
    public static void afterHandle(List<Ship_To_Affiliation__c> afterList)
    {
        set<ID> accid=new set<ID>();
        for(Ship_To_Affiliation__c sf1:afterList)
        {
            accid.add(sf1.Account__c);
        }
        list<DWCustomer__c> dwcustomerlist= new list<DWCustomer__c>();
        
        list<account> lstacc=[select id,Total_Previous_Year_Sales__c,YTD_Sale_Difference__c,name,Sales_in_Current_YearC__c,Sales_from_Last_YearC__c,Total_All_Time_SalesC__c from account where ID IN:accid];
        list<Ship_To_Affiliation__c> shplst=[select id,Total_Previous_Year_Sales__c,YTD_Sale_Difference__c,Account__c,Ship_To_Code__c,Total_Sales__c,Sales_in_Last_Year__c,Sales_in_Current_Year__c from Ship_To_Affiliation__c where Account__c IN :accid];
        
        if(checkRecursive.runOnce())
        { 
            list<DWCustomer__c> custlist2=[select id,SHIPTO_NETSALES_PYTD__c,SHIPTO_NETSALES_CYTD__c,Ship_To_Affiliation__c,SHIPTO_CUSTOMER__c,CUSTOMER_ADDRESS_4__c,CUSTOMER_ADDRESS_5__c,CUSTOMER_COUNTRY_CODE__c,CUSTOMER_POSTAL_CODE__c,CUSTOMER_ADDRESS_3__c,CUSTOMER_ADDRESS_2__c,CUSTOMER_ADDRESS_1__c,CUSTOMER_STATE__c,SALES_PERSON__c,CUSTOMER_STATE_CODE__c,CUSTOMER_COUNTRY__c,Account_Name__c,Parent_Account__c,CUSTOMER_CORPORATION_CODE__c,SHIPTO_CUSTOMER_CODE__c,SOLDTO_CUSTOMER_CODE__c from DWCustomer__c where Ship_To_Affiliation__c=null];
            system.debug('added here top');
            for(Ship_To_Affiliation__c saff:afterList)
            {
                for(DWCustomer__c dwc:custlist2)
                {
                    if(dwc.SHIPTO_CUSTOMER_CODE__c==saff.Ship_To_Code__c)
                    {
                        dwc.Ship_To_Affiliation__c=saff.id;
                        dwc.Account_Name__c=saff.Account__c;
                        dwc.Parent_Account__c=saff.Account__r.ParentId;
                        dwcustomerlist.add(dwc); 
                    }
                }
                
            }
            update dwcustomerlist;
        }
        
        for(Account acn:lstacc)
        {
            Decimal d=0;
            Decimal d1=0;
            Decimal d2=0;
            Decimal d3=0;
            Decimal d4=0;
            for(Ship_To_Affiliation__c shp:shplst)
            {
                if(shp.Sales_in_Current_Year__c!=null)
                {
                    d=d+shp.Sales_in_Current_Year__c;                  
                }
                if(shp.Sales_in_Last_Year__c!=null)
                {
                    d1=d1+shp.Sales_in_Last_Year__c;                   
                }
                if(shp.Total_Sales__c!=null)
                {
                    d2=d2+shp.Total_Sales__c;               
                }
                if(shp.YTD_Sale_Difference__c!=null)
                {
                    d3=d3+shp.YTD_Sale_Difference__c;              
                }
                if(shp.Total_Previous_Year_Sales__c!=null)
                {
                    d4=d4+shp.Total_Previous_Year_Sales__c;         
                }
                
            }
            acn.Sales_in_Current_YearC__c=d;
            acn.Sales_from_Last_YearC__c=d1;
            acn.Total_All_Time_SalesC__c=d2;
            acn.YTD_Sale_Difference__c=d3;
            acn.Total_Previous_Year_Sales__c=d4;
            
        }
        update lstacc;
    } 
    
    
}