force-app/main/default/objects/Ship_To_Affiliation__c/Ship_To_Affiliation__c.object-meta.xml
<CustomObject>
    <label>Affiliated Account</label>
    <nameField>
        <displayFormat>AFF-{00000}</displayFormat>
        <label>Affiliation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated Accounts (Account)</relationshipLabel>
    <relationshipName>Ship_To_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To_Affiliation__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Affiliated Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MyController1Test.cls
@isTest
public class MyController1Test {
    
    static testmethod void TestgetContactInfo(){
        Test.startTest();
        Account acc= new Account();
        acc.name='Test';
        insert acc;
        
        Ship_To_Affiliation__c sf =new Ship_To_Affiliation__c();
        sf.Account__c=acc.id;
        sf.Ship_To_Code__c='5789456-791040';
        insert sf;
        
        string soldcode='5789456-100570';
        MyController1.getContactInfo(acc.id);
        MyController1.accountInfo(acc.id);
        MyController1.getAccountInfo(sf.Ship_To_Code__c);
        Test.stopTest();
    }
}