force-app/main/default/objects/DW_Opportuinity_Product__c/DW_Opportuinity_Product__c.object-meta.xml
<CustomObject>
    <label>DW Opportunity Product</label>
    <nameField>
        <label>DW Opportuinity Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DW Opportunity Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/DWProduct__c.field-meta.xml
<CustomField>
    <fullName>DWProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DWProduct</label>
    <referenceTo>DWProduct__c</referenceTo>
    <relationshipName>DW_Opportuinity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>DW_Opportuinity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gusmer</fullName>
            </value>
            <value>
                <fullName>ABER</fullName>
            </value>
            <value>
                <fullName>BASF</fullName>
            </value>
            <value>
                <fullName>Bucher-Unipektin</fullName>
            </value>
            <value>
                <fullName>Bucher-Vaslin</fullName>
            </value>
            <value>
                <fullName>Chr. Hansen</fullName>
            </value>
            <value>
                <fullName>DDW</fullName>
            </value>
            <value>
                <fullName>Denwel</fullName>
            </value>
            <value>
                <fullName>DuPont</fullName>
            </value>
            <value>
                <fullName>FOSS</fullName>
            </value>
            <value>
                <fullName>Christian Gresser</fullName>
            </value>
            <value>
                <fullName>Hamilton</fullName>
            </value>
            <value>
                <fullName>Malek</fullName>
            </value>
            <value>
                <fullName>MBT</fullName>
            </value>
            <value>
                <fullName>Millipore</fullName>
            </value>
            <value>
                <fullName>Pacific Ozone</fullName>
            </value>
            <value>
                <fullName>Ponndorf</fullName>
            </value>
            <value>
                <fullName>PQ</fullName>
            </value>
            <value>
                <fullName>Pure Malt</fullName>
            </value>
            <value>
                <fullName>Renaissance Yeast</fullName>
            </value>
            <value>
                <fullName>Stellar Tan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DW_Quote_Line_Item__c/DW_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>DW Quote Line Item</label>
    <nameField>
        <label>Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DW Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DW_Quote_Line_Item__c/fields/DWProduct__c.field-meta.xml
<CustomField>
    <fullName>DWProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DWProduct</label>
    <referenceTo>DWProduct__c</referenceTo>
    <relationshipLabel>DW Quote Line Items</relationshipLabel>
    <relationshipName>DW_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DW_Quote_Line_Item__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DW_Quote_Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>DW Quote Line Items</relationshipLabel>
    <relationshipName>DW_Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DW_Quote_Line_Item__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gusmer</fullName>
            </value>
            <value>
                <fullName>ABER</fullName>
            </value>
            <value>
                <fullName>BASF</fullName>
            </value>
            <value>
                <fullName>Bucher-Unipektin</fullName>
            </value>
            <value>
                <fullName>Bucher-Vaslin</fullName>
            </value>
            <value>
                <fullName>Chr. Hansen</fullName>
            </value>
            <value>
                <fullName>DDW</fullName>
            </value>
            <value>
                <fullName>Denwel</fullName>
            </value>
            <value>
                <fullName>DuPont</fullName>
            </value>
            <value>
                <fullName>FOSS</fullName>
            </value>
            <value>
                <fullName>Christian Gresser</fullName>
            </value>
            <value>
                <fullName>Hamilton</fullName>
            </value>
            <value>
                <fullName>Malek</fullName>
            </value>
            <value>
                <fullName>MBT</fullName>
            </value>
            <value>
                <fullName>Millipore</fullName>
            </value>
            <value>
                <fullName>Pacific Ozone</fullName>
            </value>
            <value>
                <fullName>Ponndorf</fullName>
            </value>
            <value>
                <fullName>PQ</fullName>
            </value>
            <value>
                <fullName>Pure Malt</fullName>
            </value>
            <value>
                <fullName>Renaissance Yeast</fullName>
            </value>
            <value>
                <fullName>Stellar Tan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DW_Quote_Line_Item__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>TotalPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/DWProduct__c.object-meta.xml
<CustomObject>
    <description>Gusmer DW finished goods and resale items</description>
    <label>DWProduct</label>
    <nameField>
        <label>DWProduct Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DWProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DWProduct__c/fields/COMMODITY_GROUP__c.field-meta.xml
<CustomField>
    <fullName>COMMODITY_GROUP__c</fullName>
    <label>COMMODITY_GROUP</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/COMMODITY_GROUP_CODE__c.field-meta.xml
<CustomField>
    <fullName>COMMODITY_GROUP_CODE__c</fullName>
    <label>COMMODITY_GROUP_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/ITEM__c.field-meta.xml
<CustomField>
    <fullName>ITEM__c</fullName>
    <externalId>true</externalId>
    <label>ITEM</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/ITEM_DESCRIPTION__c.field-meta.xml
<CustomField>
    <fullName>ITEM_DESCRIPTION__c</fullName>
    <label>ITEM_DESCRIPTION</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_CLASS__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_CLASS__c</fullName>
    <label>PRODUCT_CLASS</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_CLASS_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_CLASS_CODE__c</fullName>
    <label>PRODUCT_CLASS_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_GROUP__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_GROUP__c</fullName>
    <label>PRODUCT_GROUP</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_GROUP_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_GROUP_CODE__c</fullName>
    <label>PRODUCT_GROUP_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_STATUS__c</fullName>
    <label>PRODUCT_STATUS</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_SUBGROUP__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_SUBGROUP__c</fullName>
    <label>PRODUCT_SUBGROUP</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_SUBGROUP_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_SUBGROUP_CODE__c</fullName>
    <label>PRODUCT_SUBGROUP_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_TYPE__c</fullName>
    <label>PRODUCT_TYPE</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_TYPE_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_TYPE_CODE__c</fullName>
    <label>PRODUCT_TYPE_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/SYS_CREATED__c.field-meta.xml
<CustomField>
    <fullName>SYS_CREATED__c</fullName>
    <label>SYS_CREATED</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/SYS_UPDATED__c.field-meta.xml
<CustomField>
    <fullName>SYS_UPDATED__c</fullName>
    <label>SYS_UPDATED</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DWOpportuinityProduct_Test.cls
@isTest
public class DWOpportuinityProduct_Test {
    static testMethod void DWOpportuinityProduct() 
    {
        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        insert testAccount;
        
        
        Contact cont = new Contact();
        cont.FirstName ='Test';
        cont.LastName ='Test';
        cont.Accountid = testAccount.id;
        insert cont;
        
        opportunity o=new opportunity();
        o.AccountId=testAccount.id;
        o.Name='Test';
        o.StageName='Closed Won';
        o.CloseDate=system.today();
        o.Supplier__c='DDW';
        // o.Pricebook2Id = standardPB;
        insert o;
        
        DWProduct__c p=new DWProduct__c();
        p.Name='test';
        p.ITEM__c='1007070001';
        p.ITEM_DESCRIPTION__c='Spectroquant PHARO 300 1 Unit';
        p.PRODUCT_TYPE_CODE__c='R';
        p.PRODUCT_TYPE__c='Resale Items';
        p.PRODUCT_GROUP_CODE__c='MIL';
        p.PRODUCT_GROUP__c='Millipore';
        p.PRODUCT_SUBGROUP_CODE__c='LAB';
        p.PRODUCT_SUBGROUP__c='Lab Essentials';
        p.PRODUCT_CLASS_CODE__c='VM';
        p.PRODUCT_CLASS__c='Resale - Millipore';
        p.COMMODITY_GROUP_CODE__c='LAB';
        p.COMMODITY_GROUP__c='Lab Essentials';
        p.SYS_CREATED__c=system.today();
        p.SYS_UPDATED__c=system.today();
        p.PRODUCT_STATUS__c='Active';
        insert p;
        
        
        DW_Opportuinity_Product__c d=new DW_Opportuinity_Product__c();
        d.Name='test';
        d.Quantity__c=1;
        d.UnitPrice__c=2;
        d.TotalPrice__c=1000;
        d.Primary__c=true;
        d.DWProduct__c=p.id;
        d.Grade__c='No comments';
        d.Opportunity__c=o.id;
        insert d;
        
        Quote q=new quote();
        q.Name='Test quote';
        q.OpportunityId=o.id;
        insert q;
        
        DW_Quote_Line_Item__c dwLineItm = new DW_Quote_Line_Item__c();
        
        dwLineItm.Quote__c=q.id;
        dwLineItm.Name='test';
        dwLineItm.Quantity__c=d.Quantity__c;
        dwLineItm.UnitPrice__c=d.UnitPrice__c;
        dwLineItm.TotalPrice__c=d.TotalPrice__c;
        dwLineItm.DWProduct__c=d.DWProduct__c;
        dwLineItm.Grade__c=d.Grade__c;
        insert dwLineItm;      
        
        o.SyncedQuoteId=q.id;
        update o;
        delete d;
        
        DW_Opportuinity_Product__c d1=new DW_Opportuinity_Product__c();
        d1.Name='test';
        d1.Quantity__c=1;
        d1.UnitPrice__c=2;
        d1.TotalPrice__c=1000;
        d1.Primary__c=true;
        d1.DWProduct__c=p.id;
        d1.Grade__c='No comments';
        d1.Opportunity__c=o.id;
        checkRecursive.Run=true;
        insert d1;
        
        checkRecursive.Run=true;
        d1.Quantity__c=2;
        update d1;
        checkRecursive.Run=true;
        delete d1;
    }
}