force-app/main/default/objects/DW_Opportuinity_Product__c/DW_Opportuinity_Product__c.object-meta.xml
<CustomObject>
    <label>DW Opportunity Product</label>
    <nameField>
        <label>DW Opportuinity Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DW Opportunity Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/DW_PriceBook_Entry__c.field-meta.xml
<CustomField>
    <fullName>DW_PriceBook_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DW PriceBook Entry</label>
    <referenceTo>DW_PriceBook_Entry__c</referenceTo>
    <relationshipName>DW_Opportuinity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/DWProduct__c.field-meta.xml
<CustomField>
    <fullName>DWProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DWProduct</label>
    <referenceTo>DWProduct__c</referenceTo>
    <relationshipName>DW_Opportuinity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/Initial_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Initial_Quantity__c</fullName>
    <label>Initial Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>DW_Opportuinity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gusmer</fullName>
            </value>
            <value>
                <fullName>ABER</fullName>
            </value>
            <value>
                <fullName>BASF</fullName>
            </value>
            <value>
                <fullName>Bucher-Unipektin</fullName>
            </value>
            <value>
                <fullName>Bucher-Vaslin</fullName>
            </value>
            <value>
                <fullName>Chr. Hansen</fullName>
            </value>
            <value>
                <fullName>DDW</fullName>
            </value>
            <value>
                <fullName>Denwel</fullName>
            </value>
            <value>
                <fullName>DuPont</fullName>
            </value>
            <value>
                <fullName>FOSS</fullName>
            </value>
            <value>
                <fullName>Christian Gresser</fullName>
            </value>
            <value>
                <fullName>Hamilton</fullName>
            </value>
            <value>
                <fullName>Malek</fullName>
            </value>
            <value>
                <fullName>MBT</fullName>
            </value>
            <value>
                <fullName>Millipore</fullName>
            </value>
            <value>
                <fullName>Pacific Ozone</fullName>
            </value>
            <value>
                <fullName>Ponndorf</fullName>
            </value>
            <value>
                <fullName>PQ</fullName>
            </value>
            <value>
                <fullName>Pure Malt</fullName>
            </value>
            <value>
                <fullName>Renaissance Yeast</fullName>
            </value>
            <value>
                <fullName>Stellar Tan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DW_Opportuinity_Product__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DW_PriceBook_Entry__c/DW_PriceBook_Entry__c.object-meta.xml
<CustomObject>
    <label>DW PriceBook Entry</label>
    <nameField>
        <label>DW PriceBook Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DW PriceBook Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DW_PriceBook_Entry__c/fields/DWProduct__c.field-meta.xml
<CustomField>
    <fullName>DWProduct__c</fullName>
    <label>DWProduct</label>
    <referenceTo>DWProduct__c</referenceTo>
    <relationshipLabel>DW PriceBook Entries</relationshipLabel>
    <relationshipName>DW_PriceBook_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DW_PriceBook_Entry__c/fields/DWProductPrices__c.field-meta.xml
<CustomField>
    <fullName>DWProductPrices__c</fullName>
    <label>DWProductPrices</label>
    <referenceTo>DWProductPrices__c</referenceTo>
    <relationshipLabel>DW PriceBook Entries</relationshipLabel>
    <relationshipName>DW_PriceBook_Entries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DW_PriceBook_Entry__c/fields/PRICEBOOK_ENTRY_KEY__c.field-meta.xml
<CustomField>
    <fullName>PRICEBOOK_ENTRY_KEY__c</fullName>
    <externalId>true</externalId>
    <label>PricebookEntryKey</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DW_PriceBook_Entry__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/DWProduct__c.object-meta.xml
<CustomObject>
    <description>Gusmer DW finished goods and resale items</description>
    <label>DWProduct</label>
    <nameField>
        <label>DWProduct Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DWProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DWProduct__c/fields/COMMODITY_GROUP__c.field-meta.xml
<CustomField>
    <fullName>COMMODITY_GROUP__c</fullName>
    <label>COMMODITY_GROUP</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/COMMODITY_GROUP_CODE__c.field-meta.xml
<CustomField>
    <fullName>COMMODITY_GROUP_CODE__c</fullName>
    <label>COMMODITY_GROUP_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/ITEM__c.field-meta.xml
<CustomField>
    <fullName>ITEM__c</fullName>
    <externalId>true</externalId>
    <label>ITEM</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/ITEM_DESCRIPTION__c.field-meta.xml
<CustomField>
    <fullName>ITEM_DESCRIPTION__c</fullName>
    <label>ITEM_DESCRIPTION</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_CLASS__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_CLASS__c</fullName>
    <label>PRODUCT_CLASS</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_CLASS_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_CLASS_CODE__c</fullName>
    <label>PRODUCT_CLASS_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_GROUP__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_GROUP__c</fullName>
    <label>PRODUCT_GROUP</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_GROUP_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_GROUP_CODE__c</fullName>
    <label>PRODUCT_GROUP_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_KEY__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_KEY__c</fullName>
    <externalId>true</externalId>
    <label>PRODUCT_KEY</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_STATUS__c</fullName>
    <label>PRODUCT_STATUS</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_SUBGROUP__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_SUBGROUP__c</fullName>
    <label>PRODUCT_SUBGROUP</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_SUBGROUP_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_SUBGROUP_CODE__c</fullName>
    <label>PRODUCT_SUBGROUP_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_TYPE__c</fullName>
    <label>PRODUCT_TYPE</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/PRODUCT_TYPE_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_TYPE_CODE__c</fullName>
    <label>PRODUCT_TYPE_CODE</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/SYS_CREATED__c.field-meta.xml
<CustomField>
    <fullName>SYS_CREATED__c</fullName>
    <label>SYS_CREATED</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DWProduct__c/fields/SYS_UPDATED__c.field-meta.xml
<CustomField>
    <fullName>SYS_UPDATED__c</fullName>
    <label>SYS_UPDATED</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DWProductPrices__c/DWProductPrices__c.object-meta.xml
<CustomObject>
    <label>DWProductPrices</label>
    <nameField>
        <label>DWProductPrices</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DWProductPrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DWProductPrices__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DWProductPrices__c/fields/LIMIT_1__c.field-meta.xml
<CustomField>
    <fullName>LIMIT_1__c</fullName>
    <label>Limit 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DWProductPrices__c/fields/LIMIT_2__c.field-meta.xml
<CustomField>
    <fullName>LIMIT_2__c</fullName>
    <label>Limit 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DWProductPrices__c/fields/PRICE_1__c.field-meta.xml
<CustomField>
    <fullName>PRICE_1__c</fullName>
    <label>Price 1</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DWProductPrices__c/fields/PRODUCT_KEY__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_KEY__c</fullName>
    <externalId>true</externalId>
    <label>PRODUCT_KEY</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DWProductPrices__c/fields/PRODUCT_REF__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_REF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DWProduct</label>
    <referenceTo>DWProduct__c</referenceTo>
    <relationshipLabel>DWProductPrices</relationshipLabel>
    <relationshipName>DWProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DWProductPrices__c/fields/SUPPLIER__c.field-meta.xml
<CustomField>
    <fullName>SUPPLIER__c</fullName>
    <label>Supplier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityDWProductEntryExtension_Test.cls
@isTest
public class OpportunityDWProductEntryExtension_Test {
    static testMethod void OpportunityDWProductEntry() 
    {
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        insert testAccount;
        
        
        opportunity o=new opportunity();
        o.AccountId=testAccount.id;
        o.Name='Test';
        o.StageName='Closed Won';
        o.CloseDate=system.today();
        o.Supplier__c='DDW';
        insert o;
        
        
        DWProduct__c p=new DWProduct__c();
        p.Name='test';
        p.ITEM__c='1007070001';
        p.ITEM_DESCRIPTION__c='Test';
        p.PRODUCT_TYPE_CODE__c='R';
        p.PRODUCT_TYPE__c='Resale Items';
        p.PRODUCT_GROUP_CODE__c='MIL';
        p.PRODUCT_GROUP__c='Millipore';
        p.PRODUCT_SUBGROUP_CODE__c='LAB';
        p.PRODUCT_SUBGROUP__c='Lab Essentials';
        p.PRODUCT_CLASS_CODE__c='VM';
        p.PRODUCT_CLASS__c='Resale - Millipore';
        p.COMMODITY_GROUP_CODE__c='LAB';
        p.COMMODITY_GROUP__c='Lab Essentials';
        p.SYS_CREATED__c=system.today();
        p.SYS_UPDATED__c=system.today();
        p.PRODUCT_STATUS__c='Active';
        
        insert p;
        
        DW_Opportuinity_Product__c d=new DW_Opportuinity_Product__c();
        d.Name='test';
        d.Quantity__c=1;
        d.UnitPrice__c=2;
        d.TotalPrice__c=1000;
        d.Primary__c=true;
        d.DWProduct__c=p.id;
        d.Grade__c='No comments';
        d.Opportunity__c=o.id;
        d.Initial_Quantity__c=5;
        insert d;
        List<DW_Opportuinity_Product__c> pdList = new List <DW_Opportuinity_Product__c> ();
        pdList.add(d);
        
        DWProductPrices__c pr = new DWProductPrices__c();
        pr.PRODUCT_REF__c=p.id;
        pr.isActive__c=true;
        pr.LIMIT_1__c=1;
        pr.LIMIT_2__c=5;
        pr.PRICE_1__c=100;
        pr.PRODUCT_KEY__c='123';
        
        insert pr;
        
        
        DW_PriceBook_Entry__c prE = new DW_PriceBook_Entry__c();
        prE.DWProduct__c=p.id;
        prE.DWProductPrices__c=pr.id;
        prE.IsActive__c=true;
        prE.Name='test';
        prE.UnitPrice__c=121;
        prE.PRICEBOOK_ENTRY_KEY__c='test';
        
        Insert PrE;
        
        Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true );
        insert pb;
        Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
        insert prod;
        PricebookEntry pbe=new PricebookEntry(unitprice=0.01,Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), IsActive= true); 
        insert pbe;
        
          Test.StartTest(); 
        PageReference pageRef = Page.OpportunityDWProductEntery_DEV;
        //Test.setCurrentPage(pageRef);
        
        Test.setCurrentPageReference(new PageReference('Page.OpportunityDWProductEntery_DEV')); 
       System.currentPageReference().getParameters().put('index', '1');
        
        pageRef.getParameters().put('Id', String.valueOf(o.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(o);
        opportunityDWProductEntryExtension_DEV oppDWcon = new opportunityDWProductEntryExtension_DEV(sc);
        
        oppDWcon.qty='1';
        oppDWcon.searchFamily = 'Test';
        oppDWcon.searchString = 'Test';
        oppDWcon.productId = p.id;
        oppDWcon.toSelect = prE.id;
        oppDWcon.selectedRow=1;
        oppDWcon.rowId = '1';
        
       
        oppDWcon.clearfilter();   
        oppDWcon.onCancel();
        oppDWcon.onSave();
        oppDWcon.onSaveAddQuotes();
         oppDWcon.searchString='test';
        oppDWcon.updateAvailableList();
        oppDWcon.quantityChange();
        oppDWcon.quantityChangeOnOpptyProd();
        
      //  oppDWcon.multipleCurrencies =true;
        oppDwcon.qty='4';
        opportunityDWProductEntryExtension_DEV.lineItems  objes= new opportunityDWProductEntryExtension_DEV.lineItems(p.id,d,true,null,false,1);         
         
        
        oppDWcon.addToShoppingCart();
        oppDWcon.savelogic();
        oppDWcon.cloneProduct();
        opportunityDWProductEntryExtension_DEV.lineItems  objes1= new opportunityDWProductEntryExtension_DEV.lineItems(p.id,d,true,null,true,1);         
        oppDWcon.savelogic();
        oppDWcon.removeFromShoppingCart();
       
        oppDWcon.savelogic();
        
        Test.stoptest();
        
        
        
        
        
        
    }
}